//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Inputs/ControlesJogador.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlesJogador: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlesJogador()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlesJogador"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""d01a1972-27dd-4bd5-bf9d-6b0d05bd0a9f"",
            ""actions"": [
                {
                    ""name"": ""Mover"",
                    ""type"": ""Value"",
                    ""id"": ""fc8de13d-6830-48d8-8633-309942a562c5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acelerar"",
                    ""type"": ""Button"",
                    ""id"": ""a45f8c20-ffb6-4cb8-8603-5bb4f9b77a66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Frear"",
                    ""type"": ""Button"",
                    ""id"": ""6430faf2-6e6e-4dac-bd97-4a5867d74b9e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pausar"",
                    ""type"": ""Button"",
                    ""id"": ""6e622b31-a56f-48ef-953f-6055a1308733"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VoltarMenuInstrucoes"",
                    ""type"": ""Button"",
                    ""id"": ""cb5a14f2-f4b7-45ca-9c56-059cbab92ae0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VoltarMenuVitoria"",
                    ""type"": ""Button"",
                    ""id"": ""d7437ac9-62d2-492a-b99c-7aaee1294214"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IniciarJogo"",
                    ""type"": ""Button"",
                    ""id"": ""54ae9783-e893-4669-87cb-fab426503138"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reiniciar"",
                    ""type"": ""Button"",
                    ""id"": ""acb51a91-77db-4dbe-b41a-9dbc1ecd7509"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Teclado WASD"",
                    ""id"": ""1313f67a-128c-48a9-bbd3-30e4864034f3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1afcc700-8080-4113-a6cb-a5e425eb02d3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f9f18fc1-75a3-4f1b-bdb8-7b8ba2002f14"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ac1b1781-fff9-430b-8115-52b6b40acabd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c910303e-0e9a-45be-b4bd-7f6a9090373e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e2f72b65-f649-495e-b635-9aa5c186980c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""509293b3-f3ce-4cba-9deb-e404c3caa329"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Setas"",
                    ""id"": ""085a84ca-321c-4369-b160-c4c757879182"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9908919c-6e7d-40eb-b61d-6502eb246239"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a87b6fc4-1e98-4a59-bb3f-44be679f8838"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f41c765b-6b5e-49e0-940e-ecf5334cbcef"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ebaa2a6a-34ab-450d-8c7c-21b1c3431aec"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""32a531b5-e2e2-4884-993c-f6381017e7c8"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acelerar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7deaca0-8a5f-4ea6-8161-22a28f4e4bdb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acelerar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8fc17a5-e75b-4c5b-9003-28af94fea07d"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Frear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2782bae1-6d85-467f-a4d1-d97feebafcc1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Frear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1e17b8c-11ff-4c58-a173-fec906291d74"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fa54866-a8de-4e71-9f76-9bf004ea2aa9"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8810c430-eb6b-457a-8045-94451548066d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoltarMenuInstrucoes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e7746c1-20a2-407e-813f-b62c89bf7e60"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoltarMenuInstrucoes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e16335d-8ae7-41ed-a1d4-6375f39e9046"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoltarMenuVitoria"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""663af624-7428-44a4-842b-1ae52e10eeea"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoltarMenuVitoria"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca8ced15-3a38-4a71-8022-5a42d3d60f4e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IniciarJogo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19450698-66f0-428a-87a9-4b07384d4e3b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IniciarJogo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f06641e-10e5-485c-b332-fc2fef5fef2f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reiniciar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e423cfd-0038-49c5-b802-31d557feaaad"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reiniciar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Mover = m_Gameplay.FindAction("Mover", throwIfNotFound: true);
        m_Gameplay_Acelerar = m_Gameplay.FindAction("Acelerar", throwIfNotFound: true);
        m_Gameplay_Frear = m_Gameplay.FindAction("Frear", throwIfNotFound: true);
        m_Gameplay_Pausar = m_Gameplay.FindAction("Pausar", throwIfNotFound: true);
        m_Gameplay_VoltarMenuInstrucoes = m_Gameplay.FindAction("VoltarMenuInstrucoes", throwIfNotFound: true);
        m_Gameplay_VoltarMenuVitoria = m_Gameplay.FindAction("VoltarMenuVitoria", throwIfNotFound: true);
        m_Gameplay_IniciarJogo = m_Gameplay.FindAction("IniciarJogo", throwIfNotFound: true);
        m_Gameplay_Reiniciar = m_Gameplay.FindAction("Reiniciar", throwIfNotFound: true);
    }

    ~@ControlesJogador()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, ControlesJogador.Gameplay.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Mover;
    private readonly InputAction m_Gameplay_Acelerar;
    private readonly InputAction m_Gameplay_Frear;
    private readonly InputAction m_Gameplay_Pausar;
    private readonly InputAction m_Gameplay_VoltarMenuInstrucoes;
    private readonly InputAction m_Gameplay_VoltarMenuVitoria;
    private readonly InputAction m_Gameplay_IniciarJogo;
    private readonly InputAction m_Gameplay_Reiniciar;
    public struct GameplayActions
    {
        private @ControlesJogador m_Wrapper;
        public GameplayActions(@ControlesJogador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mover => m_Wrapper.m_Gameplay_Mover;
        public InputAction @Acelerar => m_Wrapper.m_Gameplay_Acelerar;
        public InputAction @Frear => m_Wrapper.m_Gameplay_Frear;
        public InputAction @Pausar => m_Wrapper.m_Gameplay_Pausar;
        public InputAction @VoltarMenuInstrucoes => m_Wrapper.m_Gameplay_VoltarMenuInstrucoes;
        public InputAction @VoltarMenuVitoria => m_Wrapper.m_Gameplay_VoltarMenuVitoria;
        public InputAction @IniciarJogo => m_Wrapper.m_Gameplay_IniciarJogo;
        public InputAction @Reiniciar => m_Wrapper.m_Gameplay_Reiniciar;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Mover.started += instance.OnMover;
            @Mover.performed += instance.OnMover;
            @Mover.canceled += instance.OnMover;
            @Acelerar.started += instance.OnAcelerar;
            @Acelerar.performed += instance.OnAcelerar;
            @Acelerar.canceled += instance.OnAcelerar;
            @Frear.started += instance.OnFrear;
            @Frear.performed += instance.OnFrear;
            @Frear.canceled += instance.OnFrear;
            @Pausar.started += instance.OnPausar;
            @Pausar.performed += instance.OnPausar;
            @Pausar.canceled += instance.OnPausar;
            @VoltarMenuInstrucoes.started += instance.OnVoltarMenuInstrucoes;
            @VoltarMenuInstrucoes.performed += instance.OnVoltarMenuInstrucoes;
            @VoltarMenuInstrucoes.canceled += instance.OnVoltarMenuInstrucoes;
            @VoltarMenuVitoria.started += instance.OnVoltarMenuVitoria;
            @VoltarMenuVitoria.performed += instance.OnVoltarMenuVitoria;
            @VoltarMenuVitoria.canceled += instance.OnVoltarMenuVitoria;
            @IniciarJogo.started += instance.OnIniciarJogo;
            @IniciarJogo.performed += instance.OnIniciarJogo;
            @IniciarJogo.canceled += instance.OnIniciarJogo;
            @Reiniciar.started += instance.OnReiniciar;
            @Reiniciar.performed += instance.OnReiniciar;
            @Reiniciar.canceled += instance.OnReiniciar;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Mover.started -= instance.OnMover;
            @Mover.performed -= instance.OnMover;
            @Mover.canceled -= instance.OnMover;
            @Acelerar.started -= instance.OnAcelerar;
            @Acelerar.performed -= instance.OnAcelerar;
            @Acelerar.canceled -= instance.OnAcelerar;
            @Frear.started -= instance.OnFrear;
            @Frear.performed -= instance.OnFrear;
            @Frear.canceled -= instance.OnFrear;
            @Pausar.started -= instance.OnPausar;
            @Pausar.performed -= instance.OnPausar;
            @Pausar.canceled -= instance.OnPausar;
            @VoltarMenuInstrucoes.started -= instance.OnVoltarMenuInstrucoes;
            @VoltarMenuInstrucoes.performed -= instance.OnVoltarMenuInstrucoes;
            @VoltarMenuInstrucoes.canceled -= instance.OnVoltarMenuInstrucoes;
            @VoltarMenuVitoria.started -= instance.OnVoltarMenuVitoria;
            @VoltarMenuVitoria.performed -= instance.OnVoltarMenuVitoria;
            @VoltarMenuVitoria.canceled -= instance.OnVoltarMenuVitoria;
            @IniciarJogo.started -= instance.OnIniciarJogo;
            @IniciarJogo.performed -= instance.OnIniciarJogo;
            @IniciarJogo.canceled -= instance.OnIniciarJogo;
            @Reiniciar.started -= instance.OnReiniciar;
            @Reiniciar.performed -= instance.OnReiniciar;
            @Reiniciar.canceled -= instance.OnReiniciar;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMover(InputAction.CallbackContext context);
        void OnAcelerar(InputAction.CallbackContext context);
        void OnFrear(InputAction.CallbackContext context);
        void OnPausar(InputAction.CallbackContext context);
        void OnVoltarMenuInstrucoes(InputAction.CallbackContext context);
        void OnVoltarMenuVitoria(InputAction.CallbackContext context);
        void OnIniciarJogo(InputAction.CallbackContext context);
        void OnReiniciar(InputAction.CallbackContext context);
    }
}
